// <auto-generated />
using System;
using Kolokwium2Poprawaa.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kolokwium2Poprawaa.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240614104107_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kolokwium2Poprawaa.Models.Backpack", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("backpacks");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            ItemId = 1,
                            Amount = 1
                        },
                        new
                        {
                            CharacterId = 2,
                            ItemId = 1,
                            Amount = 1
                        },
                        new
                        {
                            CharacterId = 3,
                            ItemId = 1,
                            Amount = 1
                        },
                        new
                        {
                            CharacterId = 1,
                            ItemId = 3,
                            Amount = 2
                        },
                        new
                        {
                            CharacterId = 2,
                            ItemId = 3,
                            Amount = 2
                        },
                        new
                        {
                            CharacterId = 3,
                            ItemId = 3,
                            Amount = 2
                        },
                        new
                        {
                            CharacterId = 1,
                            ItemId = 5,
                            Amount = 1
                        },
                        new
                        {
                            CharacterId = 2,
                            ItemId = 4,
                            Amount = 1
                        },
                        new
                        {
                            CharacterId = 3,
                            ItemId = 2,
                            Amount = 1
                        });
                });

            modelBuilder.Entity("Kolokwium2Poprawaa.Models.Character", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CurrentWeight")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Character");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CurrentWeight = 73,
                            FirstName = "Krzysztof",
                            LastName = "Agaciak",
                            MaxWeight = 100
                        },
                        new
                        {
                            ID = 2,
                            CurrentWeight = 72,
                            FirstName = "Andrzej",
                            LastName = "Jackowski",
                            MaxWeight = 100
                        },
                        new
                        {
                            ID = 3,
                            CurrentWeight = 71,
                            FirstName = "Michał",
                            LastName = "Krupiewski",
                            MaxWeight = 100
                        });
                });

            modelBuilder.Entity("Kolokwium2Poprawaa.Models.Character_Titles", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AquiredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CharacterId", "TitleId");

                    b.HasIndex("TitleId");

                    b.ToTable("character_titles");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            TitleId = 4,
                            AquiredAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CharacterId = 2,
                            TitleId = 2,
                            AquiredAt = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CharacterId = 3,
                            TitleId = 1,
                            AquiredAt = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Kolokwium2Poprawaa.Models.Item", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Nóż",
                            Weight = 1
                        },
                        new
                        {
                            ID = 2,
                            Name = "Duży nóż",
                            Weight = 10
                        },
                        new
                        {
                            ID = 3,
                            Name = "Chleb",
                            Weight = 1
                        },
                        new
                        {
                            ID = 4,
                            Name = "Wędka",
                            Weight = 2
                        },
                        new
                        {
                            ID = 5,
                            Name = "Czapka",
                            Weight = 1
                        });
                });

            modelBuilder.Entity("Kolokwium2Poprawaa.Models.Title", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Title");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Żuk"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Robłów"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Kowal"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Marchewka"
                        });
                });

            modelBuilder.Entity("Kolokwium2Poprawaa.Models.Backpack", b =>
                {
                    b.HasOne("Kolokwium2Poprawaa.Models.Character", "Character")
                        .WithMany("Orders")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium2Poprawaa.Models.Item", "Item")
                        .WithMany("Backpack")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Kolokwium2Poprawaa.Models.Character_Titles", b =>
                {
                    b.HasOne("Kolokwium2Poprawaa.Models.Character", "Character")
                        .WithMany("Character_Titles")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium2Poprawaa.Models.Title", "Title")
                        .WithMany("Character_Titles")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Kolokwium2Poprawaa.Models.Character", b =>
                {
                    b.Navigation("Character_Titles");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Kolokwium2Poprawaa.Models.Item", b =>
                {
                    b.Navigation("Backpack");
                });

            modelBuilder.Entity("Kolokwium2Poprawaa.Models.Title", b =>
                {
                    b.Navigation("Character_Titles");
                });
#pragma warning restore 612, 618
        }
    }
}
